config/routes.rb
Rails.application.routes.draw do
  resources :chals
  devise_for :users
  resources :games
  resources :users
  resources :challenges

   root 'games#index'

  get 'game/' => 'games#index'
  get 'game/show' => 'games#show'

  get 'game/new' => 'games#new'

  get 'chal/' => 'chals#new'

end

app/models/chal.rb
class Chal < ActiveRecord::Base

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :white_player, :class_name => 'User', :foreign_key => 'user_white_id'
  belongs_to :black_player, :class_name => 'User', :foreign_key => 'user_black_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :white_games, foreign_key: 'user_white_id', class_name: 'Game'
	has_many :black_games, foreign_key: 'user_black_id', class_name: 'Game'
  has_many :outgoing_challenges, foreign_key: 'challenger_id', class_name: 'Challenge'
  has_many :incoming_challenges, foreign_key: 'challenged_id', class_name: 'Challenge'

  has_many :outgoing_chals, foreign_key: 'challenger', class_name: 'Chal'
  has_many :incoming_chals, foreign_key: 'challenged', class_name: 'Chal'

  def all_games
    Game.where('user_white_id = :user_id OR user_black_id = :user_id', user_id: self.id)
  end

  def all_challenges
    Challenge.where('challenger_id = :user_id OR challenged_id = :user_id', user_id: self.id)
  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
before_action :set_challenge, only: [:show, :edit, :update, :destroy]


  def index
    @challenges = Challenge.all
  end

  # GET /games/new
  def new
    @challenge = Challenge.new
  end

  # GET /games/1/edit
  def edit
  end

   def show
  end

      def set_challenge
      @challenge = Challenge.find(params[:id])
    end

  def create
    @challenge = Challenge.new(challenge_params)

     if @challenge.save
	    redirect_to :game => :index
	  else
	    @title = "Sign up"
	    render 'new'
	  end
  end



private


    def challenge_params
      params.require(:challenge).permit(:challenger, :user_id, :challenged, :challenger_id, :challenged_id)
    end



end

app/controllers/chals_controller.rb
class ChalsController < ApplicationController
  before_action :set_chal, only: [:show, :edit, :update, :destroy]

  # GET /chals
  # GET /chals.json
  def index
    @chals = Chal.all
  end

  # GET /chals/1
  # GET /chals/1.json
  def show
  end

  # GET /chals/new
  def new
    @chal = Chal.new
  end

  # GET /chals/1/edit
  def edit
  end

  # POST /chals
  # POST /chals.json
  def create
    @chal = Chal.new(chal_params)

    respond_to do |format|
      if @chal.save
        format.html { redirect_to @chal, notice: 'Chal was successfully created.' }
        format.json { render :show, status: :created, location: @chal }
      else
        format.html { render :new }
        format.json { render json: @chal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chals/1
  # PATCH/PUT /chals/1.json
  def update
    respond_to do |format|
      if @chal.update(chal_params)
        format.html { redirect_to @chal, notice: 'Chal was successfully updated.' }
        format.json { render :show, status: :ok, location: @chal }
      else
        format.html { render :edit }
        format.json { render json: @chal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chals/1
  # DELETE /chals/1.json
  def destroy
    @chal.destroy
    respond_to do |format|
      format.html { redirect_to chals_url, notice: 'Chal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chal
      @chal = Chal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chal_params
      params.require(:chal).permit(:challenger, :challenged)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:position, :text, :result, :white, :black, :user_white_id, :user_black_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/chals_helper.rb
module ChalsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenges/form.html.erb
<%= form_for Challenge.new do |f| %>


  <div class="actions">
    <%= f.submit %>


    
 <%= f.select( "challenger_id", User.all.collect {|p| [ p.email, p.id ] }, { include_blank: true }) %>
  </div>
<% end %>

app/views/chals/_form.html.erb
<%= form_for(@chal) do |f| %>
  <% if @chal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chal.errors.count, "error") %> prohibited this chal from being saved:</h2>

      <ul>
      <% @chal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :challenger  %>
 <%= f.select( "challenged", User.all.collect {|p| [ p.email, p.id ] }, { include_blank: true }) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chals/edit.html.erb
<h1>Editing Chal</h1>

<%= render 'form' %>

<%= link_to 'Show', @chal %> |
<%= link_to 'Back', chals_path %>

app/views/chals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chals</h1>

<table>
  <thead>
    <tr>
      <th>Challenger</th>
      <th>Challenged</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chals.each do |chal| %>
      <tr>
        <td><%= chal.challenger %></td>
        <td><%= chal.challenged %></td>
        <td><%= link_to 'Show', chal %></td>
        <td><%= link_to 'Edit', edit_chal_path(chal) %></td>
        <td><%= link_to 'Destroy', chal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chal', new_chal_path %>

app/views/chals/new.html.erb
<h1>New Chal</h1>

<%= render 'form' %>

<%= link_to 'Back', chals_path %>

app/views/chals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenger:</strong>
  <%= @chal.challenger %>
</p>

<p>
  <strong>Challenged:</strong>
  <%= @chal.challenged %>
</p>

<%= link_to 'Edit', edit_chal_path(@chal) %> |
<%= link_to 'Back', chals_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="actions">
    <%= f.submit %>
  </div>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :white %><br>
    <%= f.text_field :white %>
  </div>
  <div class="field">
    <%= f.label :black %><br>
    <%= f.text_field :black %>
  </div>
    <div class="field">
    <%= f.label :user_white_id %><br>
    <%= f.number_field :user_white_id %>
  </div>
    <div class="field">
    <%= f.label :user_black_id%><br>
    <%= f.number_field :user_black_id %>
  </div>

<% end %>

app/views/games/_gform.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="actions">
    <%= f.submit %>
  </div>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>


<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<% chall = Challenge.create(challenger_id: 5) %>



<h1>Your Current Games</h1>

<table>
  <thead>
    <tr>
      <th>White</th>
      <th>Black</th>
      <th>white_id</th>
      <th>Black_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% current_user.all_games.each do |game| %>
      <tr>
        <td><%= game.white %></td>
        <td><%= game.black %></td>
        <td><%= game.user_white_id %></td>
        <td><%= game.user_black_id %></td>
        <td><%= link_to 'Show', game %></td>
     
      </tr>
    <% end %>

<table>

     </tbody>
     <tbody>
<h1>Your Incoming Challenges</h1>
    <% current_user.incoming_chals.each do |chal| %>
      <tr>
          Player
      </tr>

      <tr>
        <td><%= chal.challenger %></td>
        <td><%= link_to 'Accept Challenge', new_chal_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 


<br>




<%= link_to 'New Challenge', new_chal_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div id="your_turn">
</div>
<br>

<%= render '/chessboard' %>

 <p>
  <strong>Player White:</strong>
  
  <%= User.find_by_id(@game.user_white_id).email %>
</p>
<p>
  <strong>Player Black:</strong>
  
  <%= User.find_by_id(@game.user_black_id).email %>
</p>
<p>
  <strong>User color</strong>
  <% if @game.user_white_id == current_user.id %>
    white
  <% else %>
    black
  <% end %>
</p>
<%= link_to 'Back', games_path %>

<%= render 'gform' %>

<script>
// ******************************************
var board,
  game = new Chess("<%= @game.position %>"),
  statusEl = $('#status'),
  fenEl = $('#fen'),
  pgnEl = $('#pgn');
  turnEl = $('#your_turn');
  usersTurn = true;
  userColor = (<% if @game.user_white_id == current_user.id %>'w'<% else %>'b'<% end %>);
  userColorFull = (<% if @game.user_white_id == current_user.id %>'white'<% else %>'black'<% end %>);


  var turnMsg; 
  if (userColor ===  game.turn() ){
    turnMsg = 'Its your turn!';

  } else {
    turnMsg = 'Its your opponents turn';
  }
  
  var fenField = document.getElementById("game_position");
  var turnField = document.getElementById("your_turn");

// do not pick up pieces if the game is over
// only pick up pieces for the side to move
var onDragStart = function(source, piece, position, orientation) {
  if (game.game_over() === true ||
      (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
      (game.turn() === 'b' && piece.search(/^w/) !== -1) ||
      (game.turn() !== userColor) ){
    return false;
  }
};

var onDrop = function(source, target) {
  // see if the move is legal
  var move = game.move({
    from: source,
    to: target,
    promotion: 'q' // NOTE: always promote to a queen for example simplicity
  });

  // illegal move
  if (move === null){
   return 'snapback';
 } 

  updateStatus();
};

// update the board position after the piece snap 
// for castling, en passant, pawn promotion
var onSnapEnd = function() {
  board.position(game.fen());


  // *********
  // var cfg;
  // cfg[draggable] = false;

};

var onChange = function() {
fenField.value = game.fen();
}



var updateStatus = function() {
  var status = '';

  var moveColor = 'White';
  if (game.turn() === 'b') {
    moveColor = 'Black';
  }

  // checkmate?
  if (game.in_checkmate() === true) {
    status = 'Game over, ' + moveColor + ' is in checkmate.';
  }

  // draw?
  else if (game.in_draw() === true) {
    status = 'Game over, drawn position';
  }

  // game still on
  else {
    status = moveColor + ' to move';

    // check?
    if (game.in_check() === true) {
      status += ', ' + moveColor + ' is in check';
    }
  }

  statusEl.html(status);
  fenEl.html(game.fen());
  pgnEl.html(game.pgn());
  turnEl.html(turnMsg);
};

var cfg = {
  draggable: true,

  position: "<%= @game.position %>",
  onDragStart: onDragStart,
  onDrop: onDrop,
  onSnapEnd: onSnapEnd,
  onChange: onChange

  
};
board = ChessBoard('board', cfg);
board.orientation(userColorFull);

updateStatus();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Karpov</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header class="chess-head">
  <div class="logo">
  <%= image_tag("Chess-icon.png", size: "40") %>
  </div>
  <div class="title">
  <h1>Chess Server</h1>
  <h2>Play chess online</h2>
  </div>
  </header>

	<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<br>




<br>

<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>


</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hi Player! Lets Play Chess!</h1>


<%= render '/chessboard' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>